# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#title: Your awesome title
#email: your-email@example.com
#description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
#markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#theme: jekyll-theme-tactile
title: Perl6 Interface to Gnome GTK+
description: Interfacing Perl6 to Gnome GTK+

email: mt1957@gmail.com
github_username:  MARTIMM
github: [metadata]

baseurl: "/perl6-gnome-gtk3"
#url: "https://martimm.github.io"

markdown: kramdown
highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
#kramdown:
#  input:          GFM
#  # https://github.com/jekyll/jekyll/pull/4090
#  syntax_highlighter: rouge
#
#  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
#  # span, block element options fall back to global
#  syntax_highlighter_opts:
#    # Rouge Options › https://github.com/jneen/rouge#full-options
#    css_class: 'highlight'
#    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
#    span:
#      line_numbers: false
#    block:
#      line_numbers: true
#      start_line: 1

defaults:
  -
    scope:
      path: "content-docs/reference/Gtk3"
    values:
      layout: reference-page
      title: References to the Gtk3 package modules
      nav_menu: references-nav
      sidebar_menu: references-gtk3-sidebar
  -
    scope:
      path: "content-docs/reference/Gdk3"
    values:
      layout: reference-page
      title: References to the Gdk3 package modules
      nav_menu: references-nav
      sidebar_menu: references-gdk3-sidebar
  -
    scope:
      path: "content-docs/reference/GObject"
    values:
      layout: reference-page
      title: References to the GObject package modules
      nav_menu: references-nav
      sidebar_menu: references-gobject-sidebar
  -
    scope:
      path: "content-docs/reference/Glib"
    values:
      layout: reference-page
      title: References to the Glib package modules
      nav_menu: references-nav
      sidebar_menu: references-glib-sidebar
  -
    scope:
      path: "content-docs/reference/Native"
    values:
      layout: reference-page
      title: References to the Native package modules
      nav_menu: references-nav
      sidebar_menu: references-native-sidebar
  -
    scope:
      path: "content-docs/reference/Glade"
    values:
      layout: reference-page
      title: References to the Glade package modules
      nav_menu: references-nav
      sidebar_menu: references-glade-sidebar
